# -*- coding: utf-8 -*-
"""Q8_650631043

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19VwE5mY4E6d2zGJlizQwCfQJYKShBuHv
"""

import numpy as np
m = int(input("Enter row: "))
n = int(input("Enter column: "))

r = np.full((m,n),1)
for i in range(m) : ## row
    for j in range(n) :  ## column
        if i < j and j+1 != m :
            r[i][j] = 0
        elif i == j or j+1 == m :
            r[i][j] = 1
        else :
            r[i][j] = -1
print(r)